---
title: "MODA Review"
author: "2Lt Anthony Kallhoff"
date: "March 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Accuracy

As far as I can tell, the results are accurate. The outputs are good representations of the data and mostly fall with what you expect. Since this a package designed to aid in decision making, it makes sense that it's hard to know exactly how the results will play out until you run the function. Once printed though, the output is understandable and insightful, breaking down how the results were computed. It such a minor thing that I don't want to mark off points for it, but it would be nice to know the origin of the weights for the example. 


## Compilation

No compilation issues. Package and dependcies all loaded fine. I forgot to load it to my library at first, but once I did, the functions all worked as expected. Only warning I ever got when running through the example code was 'package 'bindrcpp' was built under R version 3.4.1,' but that's not really something the package has control of. Only other thing I might add is that it is currently labeled as 'unkown' by travis. Again, not compilation issues for me so not something I'm taking into account. 

## Ease of Use

Documentation was very helpful. I had no idea what I was getting into at first, but the vignette and MODA-Package.Rd provided is a very clear example of what is happening at each step and how to use the functions. The visualization are particular insightful and helped me get a grasp of what the package was doing. 

## Grade

Outstoundaing project. (50 pts)

Now I want to find data I can use this on. 